version: '3.8'

services:
  flask:
    build: .
    command: python app_runner.py run -h 0.0.0.0
    volumes:
      - .:/flask
    expose:
      - 3000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - flask